site_name: Migrating from Ingress to Gateway API
theme:
  name: material
  features:
  - navigation.top
  - navigation.instant
  - navigation.tracking
  - navigation.footer
  - navigation.expand
  - content.code.annotate
  - content.code.copy
  palette:
    primary: teal
nav:
- index.md
- setup.md
- ingress.md
- tls.md
- migration.md
markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets:
    base_path: artifacts
    check_paths: true
- attr_list