---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookinfo-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "bookinfo.example.com"
    http:
      paths:
      - path: /productpage
        pathType: Exact
        backend:
          service:
            name: productpage
            namespace: bookinfo
            port:
              number: 9080
      - path: /static
        pathType: Prefix
        backend:
          service:
            name: productpage
            namespace: bookinfo
            port:
              number: 9080
      - path: /login
        pathType: Exact
        backend:
          service:
            name: productpage
            namespace: bookinfo
            port:
              number: 9080
      - path: /logout
        pathType: Exact
        backend:
          service:
            name: productpage
            namespace: bookinfo
            port:
              number: 9080
      - path: /api/v1/proxucts
        pathType: Prefix
        backend:
          service:
            name: productpage
            namespace: bookinfo
            port:
              number: 9080
